CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS note;

CREATE ROLE auth_user LOGIN PASSWORD 'auth_pwd';
CREATE ROLE note_user LOGIN PASSWORD 'note_pwd';

GRANT CONNECT ON DATABASE scribbly TO auth_user, note_user;

GRANT USAGE ON SCHEMA auth TO auth_user;
GRANT USAGE ON SCHEMA note TO note_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO auth_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA note GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO note_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA note GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO note_user;

ALTER ROLE auth_user IN DATABASE scribbly SET search_path = auth, public;
ALTER ROLE note_user IN DATABASE scribbly SET search_path = note, public;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;
